[project]
name = "marketing-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai[tools]>=1.9.3",
    "google-generativeai>=0.8.6",
]
